# Generated by Django 6.0.7 on 2026-07-11 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес / город')),
                ('work_hours', models.CharField(blank=True, max_length=120, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('calling', 'Нужно перезвонить'), ('confirmed', 'Подтверждена'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидание запчастей'), ('ready', 'Готово, ждёт клиента'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, help_text='Не видно клиенту. Общие заметки по заявке.', verbose_name='Внутренний комментарий менеджера')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итоговая стоимость, €')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Фото')),
                ('date_done', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выполнения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Пример работы',
                'verbose_name_plural': 'Примеры работ',
                'ordering': ['order', '-date_done'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена, €')),
                ('price_from', models.BooleanField(default=False, verbose_name='Цена от (не фиксированная)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Услуга / позиция прайс-листа',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('note', models.TextField(verbose_name='Что обсуждалось / результат звонка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Запись звонка',
                'verbose_name_plural': 'Журнал звонков',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.service', verbose_name='Интересующая услуга'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.servicecategory', verbose_name='Категория'),
        ),
    ]
