# Generated by Django 6.0.7 on 2026-07-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Технический идентификатор, например 'cpu', 'gpu'. Не менять после создания.", max_length=40, unique=True, verbose_name='Ключ (латиницей)')),
                ('name', models.CharField(max_length=120, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_required', models.BooleanField(default=True, help_text='Если выключено — категория необязательна (например, доп. периферия).', verbose_name='Обязательна для сборки')),
            ],
            options={
                'verbose_name': 'Категория комплектующих',
                'verbose_name_plural': 'Каталог: категории комплектующих',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='configuration_summary',
            field=models.TextField(blank=True, help_text='Заполняется автоматически при отправке заявки из конфигуратора сборки.', verbose_name='Собранная конфигурация'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Короткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена, €')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в конфигураторе')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Цена обновлена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='orders.partcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комплектующее',
                'verbose_name_plural': 'Каталог: комплектующие',
                'ordering': ['category__order', 'order', 'price'],
            },
        ),
    ]
