# Generated by Django 6.0.7 on 2026-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_partcategory_order_configuration_summary_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ — частые вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Обычный'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Необязательно. Если не загружено — слайдер сравнения не показывается.', null=True, upload_to='portfolio/before/', verbose_name='Фото «до»'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую, например: 1440p / игры, 3 часа работы, Гарантия 12 мес', max_length=200, verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Подтверждённый заказ'),
        ),
        migrations.AddField(
            model_name='review',
            name='service_label',
            field=models.CharField(blank=True, help_text='Например: Сборка ПК, Ремонт, Диагностика', max_length=80, verbose_name='Услуга (метка)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Фото «после»'),
        ),
    ]
