# Generated by Django 6.0.7 on 2026-07-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_faqitem_order_priority_portfolioitem_before_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='configuration_summary',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PartCategory',
        ),
    ]
