# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_configuration_summary_delete_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='order',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
    ]
