# Generated by Django 6.0.7 on 2026-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_consent_order_consent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итоговая стоимость, BYN'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена, BYN'),
        ),
    ]
